# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title CommunityC
#' @name CommunityC
#' @description Community Detection by k-means clustering using k and embedding matrix obtained in RS_PA
#' @param embedding_mat the data embedding matrix
#' @param k the number of communities
#' @param iter the number of iterations
#' @param s the list of node name
#' @return result the list of node name which in the same community
#' @examples
#' \dontrun{
#' set.seed(0)
#' n <- 100
#' p <- 3
#' embedding_mat <- matrix(rnorm(n * p), nrow = n, ncol = p)
#' s <- paste0("node", 1:n)
#' k <- 3
#' iter <- 50
#' CommunityC(embedding_mat, k, iter, s)
#' data(dolphins)
#' dolphins_mat=get.adjacency(dolphins,sparse = FALSE)
#' s=get.vertex.attribute(dolphins)$label
#' k=RS_PA(dolphins_mat,300,0.95)$k
#' embedding_mat=RS_PA(dolphins_mat,300,0.95)$embedding_mat
#' iter <- 50
#' CommunityC(embedding_mat, k, iter, s)
#' }
#' @export
CommunityC <- function(embedding_mat, k, iter, s) {
    .Call('_SA23204166_CommunityC', PACKAGE = 'SA23204166', embedding_mat, k, iter, s)
}

